#!/bin/sh

. "/usr/local/nmLNMP/cmd/common.inc"

${cmd_root}/mysql-stop
/usr/local/mysql/bin/mysqld_safe --user=nm_mysql --datadir=/home/mysql_data --skip-grant-tables &

sleep 3

if [ `ps -Af | grep mysqld | grep -vc 'grep'` = '0' ]; then
    /usr/local/mysql/bin/mysqld_safe --user=nm_mysql --datadir=/home/mysql_data --skip-grant-tables &
fi

sleep 3

if [ `ps -Af | grep mysqld | grep -vc 'grep'` = '0' ]; then
    showmsg "${color_red}MySQL密码重置失败！"    "MySQL password was reseted failed.${color_white}"
    exit;
fi

echo 'use mysql;' > /tmp/mysql_reset_password.sql;
echo 'update user set password=password("newmap") where user="root";' >> /tmp/mysql_reset_password.sql;
echo 'flush privileges;' >> /tmp/mysql_reset_password.sql;

/usr/local/mysql/bin/mysql < /tmp/mysql_reset_password.sql;
rm -f /tmp/mysql_reset_password.sql;

${cmd_root}/mysql-restart

TF="`/usr/local/mysql/bin/mysqladmin -uroot -pnewmap extended-status|grep '+----'`"
if [ ! "$TF" ]; then
    showmsg    "${color_green}MySQL密码重置成功"    "MySQL password was reseted${color_white}"
else
    showmsg "${color_red}MySQL密码重置失败！"    "MySQL password was reseted failed.${color_white}"
fi

