#!/bin/sh

data_dir='/mydata/pgsql_data'
su postgres -c "pg_ctl reload -D $data_dir -l $data_dir/pgsql.log -o -i";

if [ `ps -Af | grep "postgres" | grep -vc 'grep'` != '0' ]; then
    echo "PgSQL was reloaded successfully"
else
    su postgres -c "pg_ctl start -D $data_dir -l $data_dir/pgsql.log -o -i";

    if [ `ps -Af | grep "postgres" | grep -vc 'grep'` != '0' ]; then
        echo "PgSQL was reloaded successfully"
    else
        echo "PgSQL was reloaded failed"
    fi
fi

