#!/bin/sh

if [ `ps -Af | grep "postgres" | grep -vc 'grep'` != '0' ]; then
    echo "PgSQL is already running"
else

    pgsql_user='postgres'
    data_dir='/mydata/pgsql_data'
    chown -R ${pgsql_user}:${pgsql_user} ${data_dir}
    chmod -R 0700 ${data_dir}

    #su postgres -c "postgres -D $data_dir > $data_dir/pgsql.log 2>&1 &"
    su postgres -c "pg_ctl start -D $data_dir -l $data_dir/pgsql.log -o -i"
    chmod -R 0700 ${data_dir}
    
    sleep 1
    
    if [ `ps -Af | grep "postgres" | grep -vc 'grep'` != '0' ]; then
        echo "PgSQL was started successfully"
    else
        echo "PgSQL was started failed"
    fi
fi

